export const workExpData = [
  {
    year: "07/2022 - present",
    title: "Specialist Programmer",
    place: "Infosys Limited, India",
    duration: "",
    projectName: "AMS Buddy",
    details: [
      { subheading: "Overview" },
      {
        points: (
          <div>
            Directed the development of{" "}
            <span className="text-[#001b5e] text-lg font-semibold">
              AMS Buddy
            </span>
            , a cutting-edge generative AI solution automating business document
            creation from T-SQL stored procedures. Utilized React for frontend
            development and Python for backend operations to optimize user
            interactions and data processing efficiency.
          </div>
        ),
      },
      { subheading: "Key Responsibilities" },
      {
        points: (
          <div>
            Led React frontend development, achieving a remarkable{" "}
            <span className="text-[#001b5e] text-lg font-semibold">40%</span>{" "}
            reduction in frontend development time and enhancing user engagement
            metrics by{" "}
            <span className="text-[#001b5e] text-lg font-semibold">30%</span>.
          </div>
        ),
      },
      {
        points: (
          <div>
            Engineered Python backend functionalities, including T-SQL to
            PySpark conversion and advanced chunking strategies, resulting in a{" "}
            <span className="text-[#001b5e] text-lg font-semibold">50%</span>{" "}
            decrease in processing time for large datasets.
          </div>
        ),
      },
      {
        points: (
          <div>
            Implemented semantic search capabilities, indexing over{" "}
            <span className="text-[#001b5e] text-lg font-semibold">
              10,000{" "}
            </span>
            documents generated by{" "}
            <span className="text-[#001b5e] text-lg font-semibold">
              AMS Buddy
            </span>
            , and improving document retrieval efficiency by 25%.
          </div>
        ),
      },
      {
        points: (
          <div>
            Established and managed a comprehensive feedback loop with various
            units, resulting in a{" "}
            <span className="text-[#001b5e] text-lg font-semibold">20%</span>{" "}
            increase in user satisfaction scores and documentation quality
            ratings.
          </div>
        ),
      },
      { subheading: "VS Code Extension Development" },
      {
        points: (
          <div>
            Developed a TypeScript-based VS Code extension for semantic search,
            enhancing developer productivity by{" "}
            <span className="text-[#001b5e] text-lg font-semibold">30%</span>{" "}
            and enabling efficient code navigation within the IDE.
          </div>
        ),
      },
      { subheading: "Technologies Used" },

      {
        points: (
          <div>
            React.js, JavaScript, HTML, CSS, Python, TypeScript, VS Code
            (Tools), Git{" "}
          </div>
        ),
      },
      { subheading: "Achievements" },
      {
        points: (
          <div>
            Streamlined document generation processes, leading to a remarkable
            <span className="text-[#001b5e] text-lg font-semibold">
              50%
            </span>{" "}
            reduction in both time and effort required for document creation
            tasks.
          </div>
        ),
      },
      {
        points: (
          <div>
            Revolutionized document generation process by implementing
            innovative token chunking strategies, eliminating token limit
            constraints, and ensuring seamless operations, resulting in a{" "}
            <span className="text-[#001b5e] text-lg font-semibold">40%</span>
            increase in productivity and{" "}
            <span className="text-[#001b5e] text-lg font-semibold">
              60%
            </span>{" "}
            reduction in errors.
          </div>
        ),
      },
    ],
    isWork: true,
  },

  {
    year: "01/2022 - 05/2022",
    title: "Tech/Product Intern - (Frontend)",
    place: "Citymall, India",
    duration: "5 month",
    projectName: "CityMall Leader App",
    details: [
      {
        points: (
          <div>
            Executed shop performance feature, resulting in a{" "}
            <span className="text-[#001b5e] text-lg font-semibold">15%</span>{" "}
            increase in seller retention rates, and observed subsequent
            improvement of{" "}
            <span className="text-[#001b5e] text-lg font-semibold">15%</span>.
          </div>
        ),
      },
      {
        points: (
          <div>
            Introduced the self-deactivation feature, achieving a{" "}
            <span className="text-[#001b5e] text-lg font-semibold">30%</span>{" "}
            reduction in customer service inquiries related to account
            deactivation, thus enhancing operational efficiency and customer
            satisfaction.
          </div>
        ),
      },
      {
        points: (
          <div>
            Self deactivation initiative led to an estimated{" "}
            <span className="text-[#001b5e] text-lg font-semibold">
              20 hours
            </span>{" "}
            of saved customer support time per week.
          </div>
        ),
      },
      { subheading: "Technologies Used" },
      {
        points:
          "React Native, Redux, React-Hooks, JavaScript, HTML, CSS, VS Code (Tools), Git",
      },
    ],
    isWork: true,
  },
  {
    year: "2019 - 2022",
    title: "Master's Degree in Computer Applications",
    place: "NIT, Jamshedpur",
    duration: "3 years",
    details: [{ points: "CGPA : 8.5" }],
    isWork: false,
  },
  {
    year: "2015 - 2018",
    place: "MPCPS Kanpur",
    title: "Bachelor's Degree in Computer Applications",
    duration: "3 years",
    details: [{ points: "percentage : 70%" }],
    isWork: false,
  },
];
